build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.14"
  amd64: "ghcr.io/home-assistant/amd64-base:3.14"
  armhf: "ghcr.io/home-assistant/armhf-base:3.14"
  armv7: "ghcr.io/home-assistant/armv7-base:3.14"
  i386: "ghcr.io/home-assistant/i386-base:3.14"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Example add-on"
  org.opencontainers.image.description: "Example add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/lcmchris/thesillyhome/tree/master/src/routine_predictor/thesillyhome"
  org.opencontainers.image.licenses: "Apache License 2.0"